
project_id = "yxacicvkyusnykivbmtg"

[functions.delete-user]
verify_jwt = false

[functions.send-daily-digest]
verify_jwt = false

[functions.setup-email-digest-job]
verify_jwt = false

[functions.test-notification-email]
verify_jwt = false
