
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxacicvkyusnykivbmtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4YWNpY3ZreXVzbnlraXZibXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NDY3MTYsImV4cCI6MjA1NTQyMjcxNn0.FXjSvFChIG5t23cDV5VKHEkl82Ki-pnv64PWQjcd6jQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

/**
 * Tests the connection to Supabase
 * @returns Promise with success status
 */
export const testSupabaseConnection = async (): Promise<{ success: boolean }> => {
  try {
    if (isOffline()) {
      return { success: false };
    }
    
    // Try a simple query to test the connection
    const { error } = await supabase.from('profiles').select('id').limit(1);
    
    return { success: !error };
  } catch (error) {
    console.error("Failed to connect to Supabase", error);
    return { success: false };
  }
};

/**
 * Checks if the application is offline
 * @returns boolean indicating if the application is offline
 */
export const isOffline = (): boolean => {
  return !navigator.onLine;
};
