name: Supabase Edge Function定期実行

on:
  schedule:
    - cron: '48 20 * * *' # 毎日20:48(UTC) = 翌日5:48(JST)
  workflow_dispatch:

jobs:
  call-edge-function:
    runs-on: ubuntu-latest
    steps:
      - name: Edge FunctionにPOSTリクエスト
        run: |
          curl -X POST https://qakhgctbhyynlgajvuhr.functions.supabase.co/send-daily-digest
